<a href="https://colab.research.google.com/github/Atia6/Machine_Learning_Python/blob/main/Preprocessing/Preprocessing_Scaling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

MinMax Scaler

In [ ]:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import Binarizer

In [ ]:
data = pd.read_csv('/content/pima-indians-diabetes.csv')

In [ ]:
data.head()

6  148  72  35    0  33.6  0.627  50  1
0  1   85  66  29    0  26.6  0.351  31  0
1  8  183  64   0    0  23.3  0.672  32  1
2  1   89  66  23   94  28.1  0.167  21  0
3  0  137  40  35  168  43.1  2.288  33  1
4  5  116  74   0    0  25.6  0.201  30  0

In [ ]:
x= data.iloc[:,0:8]

In [ ]:
y= data.iloc[:,8]
y.head()

0    0
1    1
2    0
3    1
4    0
Name: 1, dtype: int64

In [ ]:
scale1= MinMaxScaler(feature_range=(0,10))

In [ ]:
scale1.fit(x)

MinMaxScaler(feature_range=(0, 10))

In [ ]:
scale1.fit_transform(x)

array([[0.58823529, 4.27135678, 5.40983607, ..., 3.96423249, 1.16567037,
        1.66666667],
       [4.70588235, 9.1959799 , 5.24590164, ..., 3.47242921, 2.53629377,
        1.83333333],
       [0.58823529, 4.47236181, 5.40983607, ..., 4.18777943, 0.38001708,
        0.        ],
       ...,
       [2.94117647, 6.08040201, 5.90163934, ..., 3.90461997, 0.71306576,
        1.5       ],
       [0.58823529, 6.33165829, 4.91803279, ..., 4.48584203, 1.15713066,
        4.33333333],
       [0.58823529, 4.67336683, 5.73770492, ..., 4.53055142, 1.01195559,
        0.33333333]])

Binarizer

In [ ]:

scale2= Binarizer(threshold= 0.5).fit_transform(x)
scale2

array([[1., 1., 1., ..., 1., 0., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 0., 1.],
       ...,
       [1., 1., 1., ..., 1., 0., 1.],
       [1., 1., 1., ..., 1., 0., 1.],
       [1., 1., 1., ..., 1., 0., 1.]])

Standardization

In [ ]:
scale3 = StandardScaler()
scale3.fit_transform(x)

array([[-0.84372629, -1.12208597, -0.16024856, ..., -0.68372895,
        -0.36426474, -0.18894038],
       [ 1.23423997,  1.94447577, -0.26357823, ..., -1.10230105,
         0.60470064, -0.1037951 ],
       [-0.84372629, -0.99692019, -0.16024856, ..., -0.49346891,
        -0.91968415, -1.0403932 ],
       ...,
       [ 0.343683  ,  0.0044061 ,  0.14974046, ..., -0.73446496,
        -0.68423462, -0.27408566],
       [-0.84372629,  0.16086333, -0.47023757, ..., -0.23978884,
        -0.37030191,  1.17338414],
       [-0.84372629, -0.8717544 ,  0.04641078, ..., -0.20173684,
        -0.47293375, -0.87010264]])